import React from 'react';
import Head from 'next/head';
import Script from 'next/script';
import { useSelector } from 'react-redux';
import TopBar from '../components/top_bar/TopBar';
import styles from '../styles/main.module.scss';
import HelpBar from '../components/help_bar/HelpBar';
import Console from '../components/center_console/Console';

const Home = () => {
  const User = useSelector((state) => state.user.value);
  //-->  lottie object styles
  const Lottiestyle = {
    width: '10%',
    height: '20%',
    cursor: 'pointer',
    position: 'absolute',
    bottom: 0,
    right: 0,
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Investing Journal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Script src='https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js' />

      {/* ----- top bar ----- */}
      <TopBar />

      {/* ----- main content area  ----- */}
      <section className={styles.main__content}>
        {/* ----- center console ----- */}
        <Console />

        {/* ----- side bar section ----- */}
        <section className={styles.side__bar}>
          {/* ----- help bar ----- */}
          <HelpBar />

          {/* ----- report ----- */}
          <lottie-player
            src='https://assets4.lottiefiles.com/packages/lf20_xh83pj1c.json'
            background='transparent'
            speed='.75'
            style={Lottiestyle}
            loop
            autoplay
          ></lottie-player>
          <span></span>
        </section>
      </section>
    </div>
  );
};

export default Home;
