import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Image from 'next/image';
import axios from 'axios';
import Link from 'next/link';
import Script from 'next/script';
import Logo from '../assets/icons/logo.svg';
import DollarImg from '../assets/icons/dollar.svg';
import BitcoinImg from '../assets/icons/bitcoin.svg';
import NikeImg from '../assets/icons/nike.svg';
import AppleImg from '../assets/icons/apple.svg';
import FaceImg from '../assets/icons/facebook.svg';
import TeslaImg from '../assets/icons/tesla.svg';
import MainImage from '../assets/images/main_image.svg';
import styles from '../styles/Home.module.scss';
import { useSelector, useDispatch } from 'react-redux';
import { login } from '../features/user';

export default function Home() {
  // pick user state from redux
  const User = useSelector((state) => state.user.value);
  const dispatch = useDispatch();

  //--------------------------------------->
  const [LoggedIn, setLoggedIn] = useState(false);
  const Images = [DollarImg, BitcoinImg, NikeImg, AppleImg, FaceImg, TeslaImg];

  // make request from api
  useEffect(() => {
    // check for token
    const UserToken = localStorage.getItem('UserToken');

    // Get user if token exists
    if (UserToken && UserToken !== null) {
      (async function () {
        try {
          await axios
            .post('https://codetivate-backend.herokuapp.com/_api/user/get', {
              token: UserToken,
            })
            .then((res) => {
              setLoggedIn(true);
              console.log(res.data);
              dispatch(login({ ...res.data.data }));
              console.log(User);
            });
        } catch (err) {
          throw err;
        }
      })();
    } else {
      console.log(`No User, token returned --> ${UserToken}`);
    }
  }, []);

  //-->  logout handler
  const handleLogout = () => {
    localStorage.removeItem('UserToken');
    setLoggedIn(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Investing Journal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Script src='https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js' />

      <main className={styles.main}>
        {/* <lottie-player
          src='https://assets4.lottiefiles.com/packages/lf20_xh83pj1c.json'
          background='transparent'
          speed='.75'
          style={{ width: '200px', height: '200px' }}
          loop
          hover
        ></lottie-player> */}
        {/* ----- logo area ----- */}
        <div className={styles.logo__container} onClick={handleLogout}>
          <Image src={Logo} alt='' />
        </div>
        {/* ----- main content div ----- */}
        <section className={styles.content__section}>
          {/* ----- title ----- */}
          <h1 className={styles.title}>INVESTING JOURNAL</h1>
          {/* ----- tag message ----- */}
          <h3 className={styles.tag__message}>-Workaholism simplified-</h3>

          {/* ----- sub text ----- */}
          <h4 className={styles.sub__text}>
            Tracking and Smart Analysis for
            <br />
            Stocks, Crypto, Forex
            <br />& more...
          </h4>

          {/* ----- call to action ----- */}
          <Link href={LoggedIn ? '/home' : '/auth'}>
            <button className={styles.main__cta}>
              {LoggedIn ? `Welcome ${User.firstname} ` : 'Get started'}
            </button>
          </Link>
        </section>

        {/* ----- image section ----- */}
        <section className={styles.abs__img_container}>
          <div className={styles.rel__img_container}>
            <Image
              src={MainImage}
              alt=''
              className={styles.main__img}
              layout='fill'
            />
          </div>
        </section>
        {/* ----- icons section ----- */}
        <span className={styles.icons__div}>
          {Images.map((image, index) => {
            return (
              <div className={styles.rel__icon_div} key={index}>
                <Image
                  src={image}
                  alt=''
                  layout='fill'
                  className={styles.icons__side}
                />
              </div>
            );
          })}
        </span>
      </main>
    </div>
  );
}
